### ISSUE TITLE
[Insight-Viewer] fluid size bug

### ISSUE THREAD

**Issue by skpark-lunit** [lunit-io/frontend-components#103]
The height of '/cornerstone-canvas' Dom element increases indefinitely, when there are no fixed size in the wrapper element.
<img width="798" alt="스크린샷 2021-08-27 오후 3 07 50" src="https://user-images.githubusercontent.com/81394944/131080279-ffed80df-246f-4e9e-b116-4a072e4b446e.png">

### Sibling 엘리먼트가 있을 때 발생한다.
**sibling 엘리먼트가 없는 경우 또는  sibling 엘리먼트가 있는데 InsightViewer를 wrapper로 감쌌을 때 : :o: OK**
```tsx
function App(): JSX.Element {
    ...
    return <InsightViewer ... />
}

// or
function App(): JSX.Element {
    ...
    return (
        <>
            <InsightViewer ... />
        </>
    )
}

// or
function App(): JSX.Element {
    ...
    return (
        <>
             <Box mb={6}>
                <Text>blah blah</Text>
            </Box>
            <div>
               <InsightViewer ... />
            </div>
        </>
    )
}

// or
function App(): JSX.Element {
    ...
    return (
        <div>
             <Box mb={6}>
                <Text>blah blah</Text>
            </Box>
            <InsightViewer ... />
        </div>
    )
}
```

**Sibling 엘리먼트가 있고, InsightViewer의 wrapper가 없으며 부모 엘리먼트가 Fragment 일 때: :x: Infinite Resizing**
```tsx
function App(): JSX.Element {
    ...
    return (
        <>
            <Box mb={6}>
                <Text>blah blah</Text>
            </Box>
            <InsightViewer ... />
        </>
    )
}
```
위의 경우 문제 발생.
'.cornerstone-canvas-wrapper' div 엘리먼트의 style은 
```js
const style = {
  position: 'relative',
  width: '100%',
  height: '100%',
  backgroundColor: '#000',
  userSelect: 'none',
  flex: 1,
} as const
```
즉 높이가 100%이다. 100% 높이는 부모 엘리먼트에 의존하는데,
Sibling 엘리먼트가 있으면서 InsightViewer의 부모 엘리먼트가 없는 경우, 
https://github.com/cornerstonejs/cornerstone/blob/ade7347d14b2cc2c28b43ae7cb1b2b0dbd09abe6/src/resize.js#L43
```js
function setCanvasSize (element, canvas) {
    ...
     // Avoid setting the same value because it flashes the canvas with IE and Edge
    if (canvas.height !== element.clientHeight) {
        canvas.height = element.clientHeight;
        canvas.style.height = `${element.clientHeight}px`;
    }
}
```
setCanvasSize()를 호출하여 리사이즈 한 후, element.clientHeight가 sibling 엘리먼트의 높이를 더 한 만큼 증가하여, setCanvasSize() 호출이 다시 발생하여 canvas가 리사이즈 된다.
이렇게 element.clientHeight가 계속 바뀌어 위와 같은 현상이 발생한 것.
resize 높이 변화 추이는 다음과 같다.
<img width="1857" alt="스크린샷 2021-09-06 오후 6 58 45" src="https://user-images.githubusercontent.com/81394944/132199487-4b57f7ab-6275-4d2b-aa0e-7468750df011.png">
Sibling element의 높이(24px) + 마진(24px) = 48px만큼 증가하는 것을 볼 수 있다.
<img width="241" alt="스크린샷 2021-09-06 오후 6 52 49" src="https://user-images.githubusercontent.com/81394944/132199005-87b5038c-cba7-4438-bee0-b374c45661d0.png">

**Comment by skpark-lunit** [comment]
> 아 이 현상 저도 예전에 insight-viewer v1 짜다가 봤는데… cornerstone.resize 콜이 wrapper 사이즈를 변경시키면서 무한히 루프하는 증상으로 기억합니다.

혹시 어떻게 해결했는지도 기억하시나요???

**Comment by deminoth** [comment]
그때는 해결을 안 하고 사용할때 항상 높이를 준거같네요 ㅎㅎ

**Comment by skpark-lunit** [comment]
@deminoth 님. 현상 파악을 [위와 같이](https://github.com/lunit-io/frontend-components/issues/103#issue-980907491) 했습니다.
결론은 캔버스 높이가 100%로 지정되어 있으나, 기준이 되는 부모 엘리먼트가 없기 때문인데요.
이건 일반 HTML 엘리먼트의 스타일에서도 발생하는 문제라서, 사용자가 올바르게 사용하도록 안내하는 수 밖에 없다는 생각이 듭니다.

**Comment by deminoth** [comment]
그러면 won't fix 달고 클로즈해도 될듯합니다. 라이브러리에서 감지해서 경고해주는 방법도 있기야 하겠지만 드는 노력에 비해 이득이 적을듯

**Comment by skpark-lunit** [comment]
> 그러면 won't fix 달고 클로즈해도 될듯합니다. 라이브러리에서 감지해서 경고해주는 방법도 있기야 하겠지만 드는 노력에 비해 이득이 적을듯

라이브러리에서 감지해서 경고해보려고 했는데요. 뷰어의 부모 엘리먼트가 Fragment인지 일반 DOM인지를 체크하여 Fragment일 때 div로 감싸는 방법을 어떻게 구현할 지 골치가 아프네요. won't fix 할게요. 좋은 방법이 생각나면 다시 이슈 열겠습니다.

**Comment by skpark-lunit** [comment]
won't fix
