### ISSUE TITLE
@lunit/insight-viewer에 cornerstone.setToPixelCoordinateSystem 호출하는 헬퍼 추가

### ISSUE THREAD

**Issue by skpark-lunit** [lunit-io/frontend-components#144]
https://github.com/lunit-io/insight-public/pull/197#issuecomment-966754911

**Comment by deminoth** [comment]
`cornerstone.setToPixelCoordinateSystem`의 사용이 필수는 아니고, 해당하는 transform을 대신해주는 함수가 있어도 됩니다. (dx, dy, dw, dh만 신경쓰면 되겠죠) `setToPixelCoordinateSystem`의 단점은 canvas에서만 적용 가능하고 svg나 다른 방법으로 직접 오버레이를 만들고 싶을 때는 사용할 수 없다는 점이라서요.

**Comment by deminoth** [comment]
서연님이 예전에 svg 오버레이를 구현한거 보니 `cornerstone.pixelToCanvas` API를 이용해 좌표값을 계산해서 그려냈네요. 이쪽 헬퍼도 있으면 쓸데가 있을듯? https://github.com/lunit-io/frontend-components/blob/3.x/src/%40lunit/insight-viewer/components/ContourViewer.tsx
