### ISSUE TITLE
monorepo 분리

### ISSUE THREAD

**Issue by deminoth** [lunit-io/frontend-components#180]
서로 의존성이 없는 패키지까지 하나의 레포로 관리하다보니 관리 부담만 커지고 시너지는 없는 상황으로 보입니다.

1. `@lunit/insight-viewer`만 남기고 `@lunit/osd-react-renderer`와 `@lunit/mui-theme`를 별도 레포로 분리

2. `@lunit/insight-viewer`, `@lunit/osd-react-renderer`, `@lunit/mui-theme`를 전부 별도 레포로 분리하고 이 레포는 레거시 컴포넌트(3.x branch) 유지보수용으로 전환

메인테이너분들 의견 주세요 @skpark-lunit @tchung1118

**Comment by skpark-lunit** [comment]
좋습니다. @tchung1118 님께 불편함을 끼쳐드려 죄송하네요.

**Comment by tchung1118** [comment]
음 넵 좋습니다! 저는 1,2번 어느쪽이든 괜찮아요.

**Comment by skpark-lunit** [comment]
그럼 인사이트 뷰어는 남을게요.

**Comment by deminoth** [comment]
그러면 mui-theme는 https://github.com/lunit-io/design-system 로 이전하겠습니다. 태원님도 새 레포로 이전 후에 알려주세요 ㅎㅎ

**Comment by tchung1118** [comment]
@hyunjin-lunit 현진님, osd-react-renderer를 새로운 repo로 이전하기로 결정함에 따라 Documentation 관련 개발은 새로운 repo로 이전된 이후에 진행하는게 좋을 듯 합니다. 이전하고 다시 알려드리겠습니다!

**Comment by tchung1118** [comment]
osd-react-renderer는 https://github.com/lunit-io/osd-react-renderer 여기로 이전했습니다. osd-viewer-demo app도 여기로 이전할 계획입니다.

**Comment by deminoth** [comment]
디렉토리 삭제되면 이슈 클로즈하겠습니다
