### ISSUE TITLE
Fetching image path before fetching actual image

### ISSUE THREAD

**Issue by zzoman** [lunit-io/frontend-components#191]
# FYI

1. We are using below flow for preparing image
> 1. Request to our image API server with `gs://` protocoled path for getting actual image path with an expiration.
> 2. Download image with the actual image path which is from `1`.
2.  Could you support above flow for `loadImage`?

----

# The problems we got for using `useMultipleImages`

```tsx
const { images } = useMultipleImages({
    web: [
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…45484191961442596137121069940267279802_ogx7cy.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…46698450950138073536948532051211540160_mjo0c0.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…48904785584257160600845535999615886933_2pn1v4.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…15529897728489595368919298983760488613_t8klwy.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…15548359998171867677666491468787711462_i5b9al.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…902796935819526283804562498881885424_2_emqmgr.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…64151404501178978088418732699745558756_sjo9dr.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…64734797879758394063944604956463769654_8zhdz1.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…66067959743194803523245438773275045460_cagahl.png',
      'gs://ctl-image-files-dev/corroboration/PadChest_pu…17051121407339296329886364436438476997_cwjf9q.png',
    ],
  });
```

We are trying to use `useMultipleImages` of insight-viewer with above kind of image path set. But sure, it was not working. 

# What is that `gs://` paths for?

On CTL, we are using `gs://` protocol for making an expiration for the request of each images. So that `gs://` path is not for the actual images, that is only for getting image paths. 

We prepare image path with requesting image API server with `gs://` protocoled path, and with the response of it, we will try to download the actual image.

```tsx
// This is the actual codes we are handling "gs://" path for getting image path before downloading image
// https://github.com/lunit-io/radiology-annotation-frontend/blob/974029610d7770dc68c3d2e714ac7208d3540d65/src/services/job.ts#L124-L137

export const getImagePath = async (
  image?: Image
): Promise<string | undefined> => {
  if (!image) return;

  const { path, width, height } = image;
  const token = getToken();

  if (path.startsWith(CONSTANTS.GS_IMG_SCHEME)) {
    const apiResponse = await imageApi.get<GoogleStorageAPIResponse>('img', {
      path,
    });
    return apiResponse.signed_url;
  } else if (path.endsWith(CONSTANTS.DICOM_SCHEME)) {
```

# The Question

There can be two options for supporting that flow.

A. Preparing all of actual image paths by ourselves before using `useMultipleImages`
B. Update `loadImage` of insight-viewer to handle fetching image path before downloading actual image

We are trying to figure out `A` by ourselves, because it feels like the flow about fetching image path through some of other API host is not that good for common library. Because we don't know how many other organizations need this kind of feature.

But, for the managing images, because it seems `useMultipleImages` is already fetching all of images sequentially, fetching image path just before downloading image is more meaningful.

- As I told above, the separated step for fetching image path is for making an expiration of it. If we prepare all of image paths at once before start of sequential downloading, those short expirations can be expired.
- If some of image loading failed, above situation will be more complexed.

**So I want to ask you about that option `B` can be acceptable for you or not.** 🙇‍♂️ 🙇‍♀️

**Comment by zzoman** [comment]
It seems like below two factors are meaningful for support this.

## requestInterceptor

https://github.com/lunit-io/frontend-components/blob/1c8094cbe18dedad4cd7647c8f639212884b4e56/packages/insight-viewer/src/utils/httpClient/index.ts#L8-L17

If [beforeRequest](https://github.com/sindresorhus/ky) is available to handle promise inside of it, then it seems we can fetch image path inside of it, and then we can set another request path with the result of previous fetch.

It seems good and quite easy because we can just give a new function as an argument of `useMultipleImages`.

## New image schema

https://github.com/lunit-io/frontend-components/blob/1c8094cbe18dedad4cd7647c8f639212884b4e56/packages/insight-viewer/src/hooks/useMultipleImages/getImageIdsAndScheme.ts#L15-L35

Simply, it seems like we need to add new schema like `GS` or `GOOGLE_STORAGE`, but it seems this image schema is affecting variable logics. 

Below will be necessary questions.

- Addition of `GS` as a static type is necessary for common library?
- What else it can affect like cornerstone loading type or ETC.

**Comment by skpark-lunit** [comment]
Sorry for the late feedback.

When implementing "requestInterceptor", I was planning only to use it for auth-related headers.
Other uses were not considered. So modifying codes is required.

Currently, "useMultipleImages()"  receives three kinds of image-related props.
(I have only focused on dicom images and haven’t tested web/dicomfile images yet as a matter of time.)

```
useMultipleImages({
  wadouri: [
    'wadouri:https://static.lunit.io/fixtures/dcm-files/series/CT000000.dcm',
      ...
  ]
})
useMultipleImages({
  web: [
    'https://rawgit.com/cornerstonejs/cornerstoneWebImageLoader/master/examples/Renal_Cell_Carcinoma.jpg',
      ...
  ]
})
```
Two image loaders are used here.
### 1. [cornerstoneWADOImageLoader](https://github.com/cornerstonejs/cornerstoneWADOImageLoader) for wadouri image: loadImage.js
  
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/e38c066a7b8c293e48b6e0ca7a21791400ce7d86/src/imageLoader/wadouri/loadImage.js#L143
```
function loadImage(imageId, options = {}) {
  const parsedImageId = parseImageId(imageId);

  options = Object.assign({}, options);
  let loader = options.loader;

  if (loader === undefined) {
    loader = getLoaderForScheme(parsedImageId.scheme);
  } else {
    delete options.loader;
   // loader is used instead below.
  }
```
If there is a custom loader, loadImage() calls it.
If not, loadImage() calls its own xhrRequest method.

### 2. [cornerstoneWebImageLoader](https://github.com/cornerstonejs/cornerstoneWebImageLoader) for web image: loadImage.js 
   https://github.com/cornerstonejs/cornerstoneWebImageLoader/blob/fd929932fe04231e42b7d3afd271d20832e22e09/src/loadImage.js#L18
```
export function loadImage (imageId) {
  const cornerstone = external.cornerstone;

  const xhr = new XMLHttpRequest();

  xhr.open('GET', imageId, true);
  xhr.responseType = 'arraybuffer';
  options.beforeSend(xhr);
```
loadImage() calls its own XMLHttpRequest().

That’s why when calling useMultipleImages() with web image, our httpClient() including requestInterceptor is not triggered.
I think we should update this file to meet your purpose.
https://github.com/lunit-io/frontend-components/blob/1c8094cbe18dedad4cd7647c8f639212884b4e56/packages/insight-viewer/src/hooks/useMultipleImages/loadCornerstoneImages.ts#L22
```
export const loadCornerstoneImages: GetLoadImage = (
  image,
  imageScheme,
  requestInterceptor
) =>
  loadImage(image, {
    loader:
      imageScheme === IMAGE_LOADER_SCHEME.DICOMFILE
        ? undefined
        : getHttpClient(requestInterceptor),
  })
```
The image paths should be resolved before calling loadImage(i.e. cornerstone.js loadImage).

**Comment by zzoman** [comment]
Close this issue because we decided not to use the new version of insight-viewer.

There are couple of things we need to implement/fix for using this, but we have not enough time for waiting/participating those. So we decided to use legacy structure for CCT support project of our CTL service.

Thank you for effort and your times for think of these requests!
