### ISSUE TITLE
In react-script 5.0.0 version, heap out of memory error occurs when importing @lunit/insight-viewer

### ISSUE THREAD

**Issue by LTakhyunKim** [lunit-io/frontend-components#192]
After setting up the React project through create-react-app.
When importing insight-viewer above, heap out of memory error occurs.
![heat out of memory error image](https://user-images.githubusercontent.com/88369343/151116564-6c7bfc1b-770c-4323-99e2-20cb368bda70.png)

It is confirmed that an error occurs after allocating memory up to 4.15GB.
If the default limit is 4 GB or more, it is confirmed that even more than that is allocated.
<img width="1782" alt="memory" src="https://user-images.githubusercontent.com/88369343/151116859-25c24f00-3f40-4675-bbcc-bdcc4b6deb9f.png">

These are the dependencies of package.json .
```json
 "dependencies": {
    "@lunit/insight-viewer": "^5.1.0-alpha.10",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "@testing-library/user-event": "^13.2.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.0"
  },
```

If downgrade react-scripts to 4.0.0, It works normally.
This happens the same in all versions.
The react-scripts version is 4.0.0 in [codesandbox example](https://codesandbox.io/s/insight-viewer-mkz4n?file=/package.json)

**Comment by deminoth** [comment]
>     "start": "GENERATE_SOURCEMAP=false react-scripts start"

이렇게 하면 개발중인 앱에서 소스맵을 사용할 수 없어 디버깅이 어려워지는 것 아닌가요? `insight-viewer`에서 해결하는 방법을 찾아봐야겠습니다.

**Comment by skpark-lunit** [comment]
> 이렇게 하면 개발중인 앱에서 소스맵을 사용할 수 없어 디버깅이 어려워지는 것 아닌가요? `insight-viewer`에서 해결하는 방법을 찾아봐야겠습니다.

네, 저건 임시방편으로 우선 메모리 힙 에러를 없앨 수 있다는 거고 근본적인 해결법이 아닙니다.
정리할게요.
- 메모리 힙 에러는 소스맵과 관련된 것으로 insight-viewer에서 해결해야 합니다. 
- webpack v5 업데이트로 인한 cornerstone-wado-image-loader의 'fs'이 브라우저에서 호환이 되지 않는 에러를 insight-viewer에서 해결해야 합니다.
- insight-viewer에서 사용하는 microbundle에서 할 수 있는 configuration은 아주 최소한의 것입니다. webpack 또는 rollup으로 바꾸어서 위의 문제를 해결하는 방법을 찾아야합니다.

**Comment by deminoth** [comment]
> 메모리 힙 에러는 소스맵과 관련된 것으로 insight-viewer에서 해결해야 합니다.

일단 최신 커밋 91edc4fa1971b36f2eef015152a1dccb61d14fe4 을 받아서 로컬 빌드 후 외부 폴더의 cra5에 설치해봤는데(`"@lunit/insight-viewer": "file:`로 설치), 해당 문제 발생하지 않았습니다. [숙경님 테스트 브랜치](https://github.com/lunit-io/frontend-components/tree/feature/react-script-v5) 받아서 해보니 문제가 재현이 되네요. cra5(또는 webpack5)가 충분조건은 아닌 듯 합니다. 이 문제 처음 리포트되었던게 어느 경로였나요?

> webpack v5 업데이트로 인한 cornerstone-wado-image-loader의 'fs'이 브라우저에서 호환이 되지 않는 에러를 insight-viewer에서 해결해야 합니다.
이건 polyfill 설치로 해결하기는 번거로우니… loader 버전을 v4로 올리는게 나을 것 같습니다. 일부 코덱 워커 관련해서 문제가 있긴 한데 해결책이 없는건 아니라서요.

**Comment by deminoth** [comment]
npm 통해 `"@lunit/insight-viewer": "^5.1.0-alpha.10",`로 설치해도 oom 에러 발생하지 않고 있네요. 해당 문제는 모노레포 구성상의 문제라고 보는 것이 맞을 것 같습니다 .

**Comment by LTakhyunKim** [comment]
> 일단 최신 커밋 https://github.com/lunit-io/frontend-components/commit/91edc4fa1971b36f2eef015152a1dccb61d14fe4 을 받아서 로컬 빌드 후 외부 폴더의 cra5에 설치해봤는데("@lunit/insight-viewer": "file:로 설치), 해당 문제 발생하지 않았습니다. [숙경님 테스트 브랜치](https://github.com/lunit-io/frontend-components/tree/feature/react-script-v5) 받아서 해보니 문제가 재현이 되네요. cra5(또는 webpack5)가 충분조건은 아닌 듯 합니다. 이 문제 처음 리포트되었던게 어느 경로였나요?

질문하신 것에 대한 답변이 될지는 모르겠지만, 해당 문제 처음 리포트 되었던 시점은 **상엽님께서 테스트 해주신 최신 커밋와 동일**합니다.
(숙경님과 로컬에서 배포 작업 당시 releases/insight-viewer 시점이 동일한 부분 확인했습니다.)

공유해주신 로컬 빌드 후 `"@lunit/insight-viewer": "file:` 방식으로 테스트 해보겠습니다.
 @skpark-lunit 님  위 내용 중 추가해주실 내용 혹은 수정이 필요한 내용이 있다면 해당 부분에 대한 보강 설명 해주시면 감사하곘습니다. 🙏
 (아무래도 당시 배포 브랜치 셋업을 숙경님께서 도와주셔서 제가 이해했던 내용과 다소 다를 수 있을 것 같아서요.)

**Comment by skpark-lunit** [comment]
# Reproduction
## 1. 타입스크립트 CRA 프로젝트 생성
```bash
$ yarn create react-app cra-demo --template typescript
```
## 2. @lunit/insight-viewer 패키지 설치
npm publish 게시오류가 안나는 동작하는 버전 설치 
https://codesandbox.io/s/insight-viewer-basic-gflz4?file=/src/App.tsx:299-367 에서 쓰고 있다.
```bash
$ yarn add @lunit/insight-viewer@5.1.0-alpha.0
```
## 3. 앱 실행
App.tsx
```tsx
import InsightViewer, { useImage } from "@lunit/insight-viewer";

const style = {
  width: "500px",
  height: "500px",
};

function App() {
  const { image } = useImage({
    wadouri:
      "wadouri:https://static.lunit.io/fixtures/dcm-files/series/CT000000.dcm",
  });

  return (
    <div style={style}>
      <InsightViewer image={image} />
    </div>
  );
}

export default App;
```

```bash
$ yarn start
```
## 결과
yarn start 실행 시 GENERATE_SOURCEMAP=false 하지 않고, 
```json
"start": "react-scripts start",
```
로 실행했는데 이번에는 메모리 힙 에러는 안나고, fs 에러만 납니다.
<img width="1184" alt="777" src="https://user-images.githubusercontent.com/81394944/152538653-221cc57c-7e26-4f6f-b45c-4a15d12bb25f.png">

## 테스트한 CRA package.json
```json
{
  "name": "cra-demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@lunit/insight-viewer": "5.1.0-alpha.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^17.0.20",
    "@types/react-dom": "^17.0.9",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by skpark-lunit** [comment]
- node v16.13.2
- npm v8.1.2
- yarn v1.22.17

**Comment by skpark-lunit** [comment]
위와 같이 이제는 OOM 문제가 발생하지 않네요.
혹시 몰라서 cra 프로젝트를 yarn create react-app으로 자바스크립트, 타입스크립트로 만들어서 테스트 해보았고,
npx create-react-app으로도 해봤는데 모두 OOM이 발생하지 않았습니다.
그런데 분명 이전에는 OOM가 발생했었기 때문에, 이전에 테스트 했던 cra 프로젝트를 다시 살펴 보았습니다.
문제가 발생하는 cra 프로젝트와 문제가 발생하지 않는 cra 프로젝트는 package.json이 동일했습니다.
그런데 이전에 만들었던 OOM이 발생하는 cra 프로젝트의 yarn.lock을 제거한 후 다시 yarn 명령으로 디펜던시를 설치하고 실행했더니
OOM 문제가 사라졌습니다.

제가 그 동안 한 일이 있긴 합니다.
CRA CLI 명령은 insight-viewer 패키지 게시가 잘되었는지 확인하기 위해 이번에 오랜만에 실행했는데요.
그랬더니 다음 warning이 떴습니다.
<img width="668" alt="666" src="https://user-images.githubusercontent.com/81394944/152684354-8cded22b-6b88-4013-9865-a14b013477e9.png">
따라서 저 안내대로 create-react-app을 uninstall을 했는데, 그 과정에서 뭔가 꼬였던 것 같네요.
이전에 OOM이 발생하던 CRA 프로젝트의 yarn.lock을 제거하고 이번에 다시 설치하니 정상동작하는 걸 봐서는요.
그런데 이 문제를 저 뿐아니라 @LTakhyunKim 님도 겪으셨으니 이 부분 확인 부탁드립니다.

**Comment by LTakhyunKim** [comment]
> 따라서 저 안내대로 create-react-app을 uninstall을 했는데, 그 과정에서 뭔가 꼬였던 것 같네요.
이전에 OOM이 발생하던 CRA 프로젝트의 yarn.lock을 제거하고 이번에 다시 설치하니 정상동작하는 걸 봐서는요.
그런데 이 문제를 저 뿐아니라 @LTakhyunKim 님도 겪으셨으니 이 부분 확인 부탁드립니다.

@skpark-lunit 님 말씀해주신 것처럼 문제 발생하던 프로젝트의 yarn.lock 을 제거하니
OOM 문제는 사라진 것으로 확인이 됩니다.

이 부분에 대해서 어떤 차이가 있는지 확인하는데, 아직 파악하지 못했습니다.
정상 동작하는 것을 보니 당황스럽네요..

**Comment by deminoth** [comment]
> 그랬더니 다음 warning이 떴습니다.

아마 숙경님 로컬에 글로벌로 설치된 create-react-app이 이전 버전의 cra를 설치하면서 디펜던시가 꼬였던게 아닐까요? 그 꼬인게 lockfile에 남아서 저희도 오류 재현이 가능했고요(이게 lockfile의 존재 의의기도 합니다 ㅎㅎ). 일단 문제 해결된것으로 간주해도 좋을 것 같습니다. 동의하시면 close 해주세요.

**Comment by skpark-lunit** [comment]
> 아마 숙경님 로컬에 글로벌로 설치된 create-react-app이 이전 버전의 cra를 설치하면서 디펜던시가 꼬였던게 아닐까요? 그 꼬인게 lockfile에 남아서 저희도 오류 재현이 가능했고요(이게 lockfile의 존재 의의기도 합니다 ㅎㅎ). 일단 문제 해결된것으로 간주해도 좋을 것 같습니다. 동의하시면 close 해주세요.

이게 맞는 것 같습니다. 아마 lock 파일까지 비교했더라면 좋았겠네요. 그 파일은 달랐을 것 같습니다. 닫을게요.
이거 발생했을 때 아찔했었는데....
그리고 이 이슈에 대해 응답을 하면서 스스로 느낀게, 오류 보고 및 질문을 제가 잘 못하고 있네요.
오픈 소스 이슈 템플릿이 왜 있는지 알겠습니다.
이 이슈 닫을게요. 도움주셔서 감사합니다.

**Comment by skpark-lunit** [comment]
OOM 문제는 로컬 글로버로 설치한 CRA 버전 업데이트 과정 중 conflict가 생긴 문제로, 더 이상 발생하지 않습니다.
남은 문제는 https://github.com/lunit-io/frontend-components/issues/193 여기서 해결하도록 합니다.
