### ISSUE TITLE
@lunit/insight-viewer/Annotation 컴퍼넌트 추가

### ISSUE THREAD

**Issue by deminoth** [lunit-io/frontend-components#197]
## Required Features

사용자가 마우스 입력을 통해 뷰어 위에 다음 요소를 추가, 수정, 삭제 할 수 있는 컴포넌트를 개발합니다.

- Arrow
- Textbox
- Free line (later)

추가된 요소는 JSON serializable 해야 합니다.

## Reference Image

From: https://3dsutq.axshare.com/#id=9es2b3&p=vr-04___tool_pannel_-_04__annotation&g=1&sc=3

<img width="911" alt="스크린샷 2022-02-22 오후 3 25 57" src="https://user-images.githubusercontent.com/495412/155074989-f207ca67-e5cf-46cb-8706-c6bfa01d46b8.png">

**Comment by LTakhyunKim** [comment]
Arrow, Textbox, Free line component 추가 작업이 완료되어 해당 issue 는 close 처리하겠습니다.

textbox: https://github.com/lunit-io/frontend-components/pull/247

arrow Line: https://github.com/lunit-io/frontend-components/pull/208

free Line: https://github.com/lunit-io/frontend-components/pull/198
