### ISSUE TITLE
Feature request: Adding dicom number from series for the wheel scroll

### ISSUE THREAD

**Issue by MaherJendoubi** [lunit-io/frontend-components#4]
![image](https://user-images.githubusercontent.com/1798510/72696221-bb515400-3b3b-11ea-8475-0e1a7e5c95e1.png)

**Comment by iamssen** [comment]
@MaherJendoubi See `useBulkImagePosition()` hook.

<https://lunit-io.github.io/frontend-components/?path=/story/insight-viewer--series-image>

<https://github.com/lunit-io/frontend-components/blob/develop/src/_packages/%40lunit/insight-viewer/hooks/useBulkImagePosition.ts>

**Comment by MaherJendoubi** [comment]
@iamssen thanks a lot for your answer.
My bad, I was not enough precise in the feature request description. It is doable to put the image position as an overlay/annotation directly on each dicom image?

 
![image](https://user-images.githubusercontent.com/1798510/72723786-e068b580-3b81-11ea-9c33-bfc24dae4a7a.png)

**Comment by MaherJendoubi** [comment]
@iamssen Thanks a lot!
