### ISSUE TITLE
Gitter channel creation request

### ISSUE THREAD

**Issue by MaherJendoubi** [lunit-io/frontend-components#5]
Hello ,
This is not an issue but rather a suggestion to encourage the communication between contributors for this awesome project by creating a new [gitter](https://gitter.im/home) channel if possible.
Best regards,
Maher

**Comment by iamssen** [comment]
@MaherJendoubi We have no plan to increase any other communication channels other than this Github issue.

This is a repository for the development byproducts of the [Lunit.inc](https://lunit.io/en/) products. We are not planning to operate as an open-source project yet.

**Comment by MaherJendoubi** [comment]
Thank you @iamssen.
